# HTTP Server
server:
  port: ${PORT:8761}

# Configure this Discovery Server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

  # https://github.com/spring-cloud/spring-cloud-netflix/issues/413
  instance:
    hostname: localhost